### ISSUE TITLE
is this a good fit for javascript?

### ISSUE THREAD

**Issue by humanchimp** [jeffmo/es-trailing-function-commas#10]
I wonder if adding this to JS is a good idea. I see the benefit when it comes to attribution, and I am a user of trailing commas in arrays and object literals. However, I see it as a potential footgun, in the absence of a type system, wrt function parameters. I have actually shot myself in the foot this way in babel, where this feature has been implemented. The hazard goes like this.

``` javascript
  // Start with some code like this:
  foo() { return calculateFoo(42, this.bar()); }
```

Later:

``` javascript
  // Try to do something slightly fancier, but human error creeps in:
  foo() {
    let bar = this.bar();
    // Operate on `bar`
    return calculateFoo(42, ); // Whoops!
  }
```

And now `calculateFoo` has `undefined` for `bar` because after cutting `this.bar()`, I didn't replace it with anything. This will lead to a runtime error, or possibly a silent failure, whereas in the past, a mistake like that would be a syntax error.

**Comment by jeffmo** [comment]
Thanks for the issue!

In your example the problem is really that there's nothing linking the call-site to the definition (as you point out: Type systems like Flow and TypeScript are good at this today). However it's just as easy to accidentally delete the comma while refactoring as it is to delete just the param, so relying on a trailing comma as a syntax error is a fairly narrow hedge against this problem in reality.

Most langs that do solve this problem do so by enforcing proper arity somehow (either statically or dynamically) -- but doing something like that would unfortunately be a breaking change in JS :(

If only we had rest params to begin with!
